### ISSUE TITLE
Updating Chef Attributes removes Repository Authentication

### ISSUE THREAD

**Issue by BerndKue** [sapcc/lyra-cli#10]
I created a new automation using lyra cli including Repository Authentication. 
Checking the properties with lyra I could see `repository_authentication_enabled = true`

Later on I updated the chef attributes using the command `automation update chef attributes --automation-id=<my id> --attributes-from-file=<my attributes file>`

Afterwards the properties returned from the command showed `repository_authentication_enabled = false`

Since there is no command to update the Repository Authentication, I have to delete the automation and create a new one with the right chef attributes.

Could you please have a look if it is possible not to remove the repository authentication when updating the chef attributes?

Thanks, Bernd

**Comment by ArtieReus** [comment]
@BerndKue thank you for the input. I will check and update the cli accordantly.

**Comment by ArtieReus** [comment]
issue reproducible:
┏d063222@C02X76QJJGH6 /Users/d063222/go/src/github.com/sapcc/lyra-cli u8s:[qa-de-1|default] cc:[c-eu-nl-1--s-09-are] git:(master)
┗➜  go run main.go automation show --automation-id 70
Using token authentication.
![Bildschirmfoto 2022-01-24 um 16 48 44](https://user-images.githubusercontent.com/1876079/150816410-8925ebe3-f84b-459a-9da7-2e535654db43.png)

┏d063222@C02X76QJJGH6 /Users/d063222/go/src/github.com/sapcc/lyra-cli u8s:[qa-de-1|default] cc:[c-eu-nl-1--s-09-are] git:(master)
┗➜  go run main.go automation update chef attributes  --automation-id 70 --attributes '{"test":"test"}'
Using token authentication.
![Bildschirmfoto 2022-01-24 um 16 48 51](https://user-images.githubusercontent.com/1876079/150816425-aea8e5a7-c3c6-47a1-9287-3aabdf04d5cf.png)

@BerndKue nice catch!!
