### ISSUE TITLE
Writing info to stderr

### ISSUE THREAD

**Issue by BerndKue** [sapcc/lyra-cli#2]
Hi,

there are several messages written to stderr like this one for example:
https://github.com/sapcc/lyra-cli/blob/master/cmd/root.go#L182

Since this is no error, it should not be written to stderr but rather to stdout.

Best Regards
Bernd

**Comment by ArtieReus** [comment]
It is written to stderr because we want to keep the results clean to be reused for example in a pipeline.

**Comment by BerndKue** [comment]
I understand but the same way I find it disturbing when there is something written to stderr when there is no error.
How about only writing it to stdout when there is a verbose parameter provided? This message is anyway not essential.

**Comment by ArtieReus** [comment]
I will consider that once we have a verbose option. For now I will close the issue. Thx
