### ISSUE TITLE
lyra-cli does not run on M1 architecture

### ISSUE THREAD

**Issue by vandlol** [sapcc/lyra-cli#8]
Hey Guys,
lyra-darwin will not run on a M1 Mac.

**Comment by Finkregh** [comment]
supposedly closed via https://github.com/sapcc/lyra-cli/commit/dab996bf49cfb416c0119fcda487eae12f7163bb

**Comment by ArtieReus** [comment]
We tested the amd64 binary with M1 architecture and works fine. Thx for the advice!
